  task: AzurePowerShell@4
    inputs:
      azureSubscription: 'MPN'
      ScriptType: 'InlineScript'
      Inline: 'Write-Output  "This is an example"
      Write-Output "This is another one"'
      azurePowerShellVersion: 'LatestVersion'