stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'Ubuntu-16.04'
    continueOnError: true
    steps:
    - script: echo "hello to my first Build"
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'Snyk Scan'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true

