steps:
- task: AzurePowerShell@3
  displayName: 'Azure PowerShell script: InlineScript'
  inputs:
    
    ScriptType: InlineScript
    Inline: |
     Write-Output  "This is an example"
     Write-Output "This is another one"
    azurePowerShellVersion: LatestVersion